name: Grafana Deploy

on:
  push:
    paths:
      - 'grafana/**' # triggered if any modification at grafana/

jobs:
  terraform:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - uses: hashicorp/setup-terraform@v2
      
      - name: Terraform Apply
        env:
          GRAFANA_TOKEN: ${{ secrets.GRAFANA_TOKEN }}
          DB_PASSWORD: ${{ secrets.DB_PASSWORD }}
        run: |
          cd grafana
          terraform init
          terraform apply -auto-approve
