name: Grafana Deploy

on:
  push:
    paths:
      - 'grafana/**' # triggered if any modification at grafana/

jobs:
  terraform:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      
      - name: Setup Terraform
        uses: hashicorp/setup-terraform@v2
        with:
          cli_config_token: ${{ secrets.TF_API_TOKEN }}
      
      - name: Terraform Apply
        env:
          TF_VAR_grafana_auth: ${{ secrets.GRAFANA_TOKEN }}
          TF_VAR_db_password: ${{ secrets.DB_PASSWORD }}
        run: |
          cd grafana
          terraform init
          terraform apply -auto-approve -input=false